-- MySQL Script generated by MySQL Workbench
-- Fri Aug 10 18:42:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tenis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tenis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tenis` DEFAULT CHARACTER SET utf8 ;
USE `tenis` ;

-- -----------------------------------------------------
-- Table `tenis`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`endereco` (
  `id` INT NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenis`.`recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`recepcionista` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_pessoa_endereco_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_pessoa_endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `tenis`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenis`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`responsavel` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  INDEX `fk_pessoa_endereco_idx` (`endereco_id` ASC),
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_pessoa_endereco000`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `tenis`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenis`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`turma` (
  `idturma` INT NOT NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenis`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`aluno` (
  `matricula` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  `responsavel_cpf` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_pessoa_endereco_idx` (`endereco_id` ASC),
  INDEX `fk_aluno_responsavel1_idx` (`responsavel_cpf` ASC),
  INDEX `fk_aluno_turma1_idx` (`turma_idturma` ASC),
  CONSTRAINT `fk_pessoa_endereco0`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `tenis`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_responsavel1`
    FOREIGN KEY (`responsavel_cpf`)
    REFERENCES `tenis`.`responsavel` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `tenis`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenis`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`professor` (
  `siap` VARCHAR(45) NOT NULL,
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`siap`),
  INDEX `fk_pessoa_endereco_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_pessoa_endereco00`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `tenis`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tenis`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tenis`.`aula` (
  `idaulas` INT NOT NULL,
  `codigosala` INT NOT NULL,
  `duracao` VARCHAR(45) NOT NULL,
  `professor_siap` VARCHAR(45) NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`idaulas`),
  INDEX `fk_aulas_professor1_idx` (`professor_siap` ASC),
  INDEX `fk_aulas_turma1_idx` (`turma_idturma` ASC),
  CONSTRAINT `fk_aulas_professor1`
    FOREIGN KEY (`professor_siap`)
    REFERENCES `tenis`.`professor` (`siap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aulas_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `tenis`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
