/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Danilo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Consultar_Aluno = new javax.swing.JMenuItem();
        Consultar_Professor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Cadastro_Aluno = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Cadastro_Endereco = new javax.swing.JMenuItem();
        Cadastro_Responsavel = new javax.swing.JMenuItem();
        Cadastro_Professor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seja Bem Vindo ao sistema que vai gerenciar sua escola de Tênis!");

        jLabel2.setText("Até então temos implemntado: ");

        jLabel3.setText("O cadastro de Responsáveis, Alunos, Professores, Aula, Endereco");

        jLabel4.setText("Consultas de aulas dos Professores e Alunos.");

        jLabel5.setText("Sistema de Login.");

        jLabel6.setText("Em breve teremos:");

        jLabel7.setText("Calendario com todas aulas.");

        jLabel8.setText("Busca rápida de turmas!");

        jMenu1.setText("Consulta Aulas");

        Consultar_Aluno.setText("Aluno");
        Consultar_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_AlunoActionPerformed(evt);
            }
        });
        jMenu1.add(Consultar_Aluno);

        Consultar_Professor.setText("Professor");
        Consultar_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_ProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(Consultar_Professor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

        Cadastro_Aluno.setText("Aluno");
        Cadastro_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_AlunoActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Aluno);

        jMenuItem8.setText("Aulas");
        jMenu2.add(jMenuItem8);

        Cadastro_Endereco.setText("Endereço");
        Cadastro_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_EnderecoActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Endereco);

        Cadastro_Responsavel.setText("Responsavel");
        Cadastro_Responsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_ResponsavelActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Responsavel);

        Cadastro_Professor.setText("Professor");
        Cadastro_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_ProfessorActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Professor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void Consultar_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_AlunoActionPerformed
        // TODO add your handling code here:
        Consulta_Aluno objeto = Consulta_Aluno.getInstancia();
        objeto.setVisible(true);
        //new Consulta_Aluno().setVisible(true);
        
    }//GEN-LAST:event_Consultar_AlunoActionPerformed

    private void Consultar_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_ProfessorActionPerformed
        // TODO add your handling code here: 
        Consulta_Prof objeto = Consulta_Prof.getInstancia();
        objeto.setVisible(true);
    }//GEN-LAST:event_Consultar_ProfessorActionPerformed

    private void Cadastro_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_AlunoActionPerformed
        // TODO add your handling code here:
        Cadastra_Aluno objeto = Cadastra_Aluno.getInstancia();
        objeto.setVisible(true);
    }//GEN-LAST:event_Cadastro_AlunoActionPerformed

    private void Cadastro_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_ProfessorActionPerformed
        // TODO add your handling code here:
        Cadastrar_Professor objeto = Cadastrar_Professor.getInstancia();
        objeto.setVisible(true);
    }//GEN-LAST:event_Cadastro_ProfessorActionPerformed

    private void Cadastro_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_EnderecoActionPerformed
        // TODO add your handling code here:
        Cadastrar_Endereco objeto = Cadastrar_Endereco.getInstancia();
        objeto.setVisible(true);
    }//GEN-LAST:event_Cadastro_EnderecoActionPerformed

    private void Cadastro_ResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_ResponsavelActionPerformed
        // TODO add your handling code here:
        Cadastrar_Responsavel objeto = Cadastrar_Responsavel.getInstancia();
        objeto.setVisible(true);
    }//GEN-LAST:event_Cadastro_ResponsavelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadastro_Aluno;
    private javax.swing.JMenuItem Cadastro_Endereco;
    private javax.swing.JMenuItem Cadastro_Professor;
    private javax.swing.JMenuItem Cadastro_Responsavel;
    private javax.swing.JMenuItem Consultar_Aluno;
    private javax.swing.JMenuItem Consultar_Professor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
